# image will be published to ghcr.io/<user>/<name>
name: my-bluebuild
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.
  - type: rpm-ostree
    repos: 
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%OS_VERSION%/swayfx-swayfx-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/repo/fedora-%OS_VERSION%/patrickl-yabridge-fedora-%OS_VERSION%.repo
    - https://raw.githubusercontent.com/Luiza1011/swayfx-blue-personal/live/vivaldi.repo
    - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/lchh/navidrome/repo/fedora-%OS_VERSION%/lchh-navidrome-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/luiza1011/Lu-dotfiles/repo/fedora-%OS_VERSION%/luiza1011-Lu-dotfiles-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/szpadel/spotifyd/repo/fedora-%OS_VERSION%/szpadel-spotifyd-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/champe20/apx/repo/fedora-%OS_VERSION%/champe20-apx-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/fnux/ly/repo/fedora-%OS_VERSION%/fnux-ly-fedora-%OS_VERSION%.repo
    
    install:
    - starship
    - rust
    - cargo    
    - python-pip
    - go
    - zsh
    - zsh-autosuggestions
    - tmux
    - dialog
    
    - unrar
    - p7zip 
    - p7zip-plugins
    
    - terminator
    - swayfx
    - rofi
    - swaync
    - waybar
    - network-manager-applet
    - sddm
    
    - neovim
    - pavucontrol
    - blueman
    - htop
    - mc
    - fastfetch
    - nemo
    - nemo-fileroller
    - grim
    - pamixer
    - playerctl
    - polkit-gnome
    - firewall-config
    - seahorse
    - steam
    - azote
    - nwg-look
    - ffmpeg
    - ly
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
       - org.gnome.Boxes
       - org.gnome.clocks
       - org.gnome.FontManager
       - org.fedoraproject.MediaWriter
       - com.github.tchx84.Flatseal
       - org.gustavoperedo.FontDownloader
       - com.github.GradienceTeam.Gradience 
       - io.mpv.Mpv
       - org.rncbc.qpwgraph
       - org.gimp.GIMP
       - org.prismlauncher.PrismLauncher
       - net.pcsx2.PCSX2  
       - org.DolphinEmu.dolphin-emu
       - com.usebottles.bottles
       - dev.vencord.Vesktop
       - org.libreoffice.LibreOffice
       - md.obsidian.Obsidian
       - io.github.giantpinkrobots.varia
       - com.transmissionbt.Transmission
       - com.visualstudio.code
       - org.gtk.Gtk3theme.adw-gtk3 
       - org.gtk.Gtk3theme.adw-gtk3-dark  
       - runtime/org.kde.KStyle./x86_64/6.5 
       - runtime/org.kde.KStyle.Kvantum/x86_64/latest 
       - runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/6.6
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
